//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Images
    {
        public string ImageId { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string TagId { get; set; }
        public string ImageLink { get; set; }
        public string ThumbnailLink { get; set; }
        public string Tag { get; set; }
    }
}
